Rails.application.routes.draw do
  root 'welcome#index'
  get '/home' => 'welcome#index'
  get '/about' => 'pages#about'
  get '/abrahamOrTerah' => 'pages#abrahamOrTerah'
  get '/daniel' => 'pages#daniel'
  get '/fearfully' => 'pages#fearfully'
  get '/foundation' => 'pages#foundation'
  get '/gogAndMagog' => 'pages#gogAndMagog'
  get '/hebrews' => 'pages#hebrews'
  get '/jerusalemStory' => 'pages#jerusalemStory'
  get 'jesusReturns' => 'pages#jesusReturns'
  get '/noVision' => 'pages#noVision'
  get '/oldTestament' => 'pages#oldTestament'
  get '/predestination' => 'pages#predestination'
  get '/rainbow' => 'pages#rainbow'
  get '/revelation' => 'pages#revelation'
  get '/sevenPowers' => 'pages#sevenPowers'
  get '/toGodBeTheGlory' => 'pages#toGodBeTheGlory'
  get '/unveiling' => 'pages#unveiling'
  get '/job' => 'pages#job'
  get '/nephilim' => 'pages#nephilim'
  get '/appeal' => 'pages#appeal'
  get '/desire' => 'pages#desire'
  get '/nation' => 'pages#great_nation'
  get '/walking' => 'pages#walking'
  get '/light' => 'pages#light'
  get '/wept' => 'pages#wept'
  get '/samson' => 'pages#samson'
end

